[files]
extend-exclude = ["vendor/**"]

[default.extend-words]
caf = "caf"
crpyto = "crpyto"
Iz = "Iz"
IY = "IY"
Ono = "Ono"
ono = "ono"
tipe = "tipe"

[type.rime]
extend-glob = ["*.schema.yaml"]

[type.rime.extend-words]
ue = "ue"
