import AppKit
import XCTest
@testable import RillCore
@testable import RillPlatform

@MainActor
final class PasteboardControllerTests: XCTestCase {
    func testWritePlainTextMarksWrittenChangeAsOwned() {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let controller = SystemClipboardPort(pasteboard: pasteboard)

        let changeCount = controller.writePlainText("owned by Rill")

        XCTAssertEqual(pasteboard.string(forType: .string), "owned by Rill")
        XCTAssertTrue(controller.isOwnedChangeCount(changeCount))
    }

    func testPasteboardProtectionTypesAreClassifiedWithoutReadingPayload() {
        let protections = SystemClipboardPort.protections(
            forPasteboardTypeNames: [
                "public.utf8-plain-text",
                "org.nspasteboard.ConcealedType",
                "org.nspasteboard.TransientType",
                "org.nspasteboard.AutoGeneratedType",
            ]
        )

        XCTAssertEqual(protections, [.concealed, .transient, .autoGenerated])
    }

    func testOrdinaryPasteboardTypesHaveNoProtectionFlags() {
        let protections = SystemClipboardPort.protections(
            forPasteboardTypeNames: [
                "public.utf8-plain-text",
                "public.png",
                "public.file-url",
            ]
        )

        XCTAssertTrue(protections.isEmpty)
    }

    func testPlainTextCaptureEnforcesUTF8BudgetBeforeSnapshotProjection() async throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        var limits = SystemClipboardStorageLimits.productDefault
        limits.maximumTextUTF8ByteCount = 4
        let controller = SystemClipboardPort(
            pasteboard: pasteboard,
            storageLimits: limits
        )

        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.setString("éé", forType: .string))
        let acceptedValue = await controller.readSnapshot(
            ifChangeCountIs: pasteboard.changeCount
        )
        let accepted = try XCTUnwrap(acceptedValue)
        XCTAssertEqual(accepted.plainText, "éé")
        XCTAssertNil(accepted.captureStorageRejection)

        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.setString("ééé", forType: .string))
        let rejectedValue = await controller.readSnapshot(
            ifChangeCountIs: pasteboard.changeCount
        )
        let rejected = try XCTUnwrap(rejectedValue)
        XCTAssertTrue(rejected.plainText.isEmpty)
        XCTAssertEqual(rejected.captureStorageRejection, .itemTooLarge)
        XCTAssertFalse(rejected.hasTransferableContent)
    }

    func testFileURLCaptureEnforcesCountBudgetBeforeSnapshotProjection() async throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        var limits = SystemClipboardStorageLimits.productDefault
        limits.maximumFileURLCount = 1
        let controller = SystemClipboardPort(
            pasteboard: pasteboard,
            storageLimits: limits
        )
        pasteboard.clearContents()
        XCTAssertTrue(
            pasteboard.writeObjects([
                NSURL(fileURLWithPath: "/tmp/rill-first"),
                NSURL(fileURLWithPath: "/tmp/rill-second"),
            ])
        )

        let readValue = await controller.readSnapshot(
            ifChangeCountIs: pasteboard.changeCount
        )
        let snapshot = try XCTUnwrap(readValue)

        XCTAssertTrue(snapshot.fileURLs.isEmpty)
        XCTAssertEqual(snapshot.captureStorageRejection, .itemTooLarge)
        XCTAssertFalse(snapshot.hasTransferableContent)
    }

    func testImageCaptureAcceptsValidPNGWithinConfiguredBudget() async throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let pngData = try makePNGData()
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.setData(pngData, forType: .png))
        let controller = SystemClipboardPort(pasteboard: pasteboard)

        let readSnapshot = await controller.readSnapshot(
            ifChangeCountIs: pasteboard.changeCount
        )
        let snapshot = try XCTUnwrap(readSnapshot)

        XCTAssertEqual(snapshot.imagePNGData, pngData)
        XCTAssertNil(snapshot.captureStorageRejection)
    }

    func testImageCaptureFailsClosedWhenPasteboardChangesDuringDetachedProcessing() async throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let pngData = try makePNGData()
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.setData(pngData, forType: .png))
        let expectedChangeCount = pasteboard.changeCount
        let workerGate = PasteboardImageWorkerGate()
        let controller = SystemClipboardPort(
            pasteboard: pasteboard,
            imageProcessingGate: {
                await workerGate.blockWorker()
            }
        )

        let readTask = Task {
            await controller.readSnapshot(ifChangeCountIs: expectedChangeCount)
        }
        await workerGate.waitUntilBlocked()
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.setString("external winner", forType: .string))
        await workerGate.releaseWorker()

        let snapshot = await readTask.value
        XCTAssertNil(snapshot)
        XCTAssertEqual(pasteboard.string(forType: .string), "external winner")
    }

    func testConcurrentImageReadsForSameChangeCountShareOneWorker() async throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let pngData = try makePNGData()
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.setData(pngData, forType: .png))
        let expectedChangeCount = pasteboard.changeCount
        let workerGate = PasteboardImageWorkerGate()
        let controller = SystemClipboardPort(
            pasteboard: pasteboard,
            imageProcessingGate: {
                await workerGate.blockWorker()
            }
        )

        let firstRead = Task {
            await controller.readSnapshot(ifChangeCountIs: expectedChangeCount)
        }
        await workerGate.waitUntilInvocationCount(1)
        let secondRead = Task {
            await controller.readSnapshot(ifChangeCountIs: expectedChangeCount)
        }
        for _ in 0 ..< 20 {
            await Task.yield()
        }
        await workerGate.releaseAllWorkers()

        let firstReadValue = await firstRead.value
        let secondReadValue = await secondRead.value
        let firstSnapshot = try XCTUnwrap(firstReadValue)
        let secondSnapshot = try XCTUnwrap(secondReadValue)
        let statistics = await workerGate.statistics()
        XCTAssertEqual(firstSnapshot.imagePNGData, pngData)
        XCTAssertEqual(secondSnapshot.imagePNGData, pngData)
        XCTAssertEqual(statistics.invocationCount, 1)
        XCTAssertEqual(statistics.maximumConcurrentWorkerCount, 1)
    }

    func testChangedImageWaitsForOldWorkerAndDiscardsOldResult() async throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let oldPNGData = try makeImageData(using: .png, width: 2, height: 2)
        let newPNGData = try makeImageData(using: .png, width: 3, height: 2)
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.setData(oldPNGData, forType: .png))
        let oldChangeCount = pasteboard.changeCount
        let workerGate = PasteboardImageWorkerGate()
        let controller = SystemClipboardPort(
            pasteboard: pasteboard,
            imageProcessingGate: {
                await workerGate.blockWorker()
            }
        )

        let oldRead = Task {
            await controller.readSnapshot(ifChangeCountIs: oldChangeCount)
        }
        await workerGate.waitUntilInvocationCount(1)

        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.setData(newPNGData, forType: .png))
        let newChangeCount = pasteboard.changeCount
        let newRead = Task {
            await controller.readSnapshot(ifChangeCountIs: newChangeCount)
        }
        for _ in 0 ..< 20 {
            await Task.yield()
        }

        await workerGate.releaseNextWorker()
        let oldReadValue = await oldRead.value
        XCTAssertNil(oldReadValue)
        await workerGate.waitUntilInvocationCount(2)
        await workerGate.releaseNextWorker()

        let newReadValue = await newRead.value
        let newSnapshot = try XCTUnwrap(newReadValue)
        let newSnapshotData = try XCTUnwrap(newSnapshot.imagePNGData)
        let statistics = await workerGate.statistics()
        XCTAssertEqual(NSBitmapImageRep(data: newSnapshotData)?.pixelsWide, 3)
        XCTAssertEqual(newSnapshot.changeCount, newChangeCount)
        XCTAssertEqual(statistics.invocationCount, 2)
        XCTAssertEqual(statistics.maximumConcurrentWorkerCount, 1)
    }

    func testImageCaptureRejectsPNGOverConfiguredBudgetWithoutPayloadProjection() async throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let pngData = try makePNGData()
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.setData(pngData, forType: .png))
        var limits = SystemClipboardStorageLimits.productDefault
        limits.maximumImageByteCount = pngData.count - 1
        let controller = SystemClipboardPort(
            pasteboard: pasteboard,
            storageLimits: limits
        )

        let readSnapshot = await controller.readSnapshot(
            ifChangeCountIs: pasteboard.changeCount
        )
        let snapshot = try XCTUnwrap(readSnapshot)

        XCTAssertNil(snapshot.imagePNGData)
        XCTAssertEqual(snapshot.captureStorageRejection, .itemTooLarge)
        XCTAssertFalse(snapshot.hasTransferableContent)
    }

    func testImageCaptureRejectsMalformedPNGWithFormatReason() async throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.setData(Data("not-a-png".utf8), forType: .png))
        let controller = SystemClipboardPort(pasteboard: pasteboard)

        let readSnapshot = await controller.readSnapshot(
            ifChangeCountIs: pasteboard.changeCount
        )
        let snapshot = try XCTUnwrap(readSnapshot)

        XCTAssertNil(snapshot.imagePNGData)
        XCTAssertEqual(snapshot.captureStorageRejection, .imageRepresentationInvalid)
    }

    func testImageCaptureRejectsContentWhoseEncodingDoesNotMatchDeclaredPNGType() async throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let jpegData = try makeImageData(using: .jpeg)
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.setData(jpegData, forType: .png))
        let controller = SystemClipboardPort(pasteboard: pasteboard)

        let readSnapshot = await controller.readSnapshot(
            ifChangeCountIs: pasteboard.changeCount
        )
        let snapshot = try XCTUnwrap(readSnapshot)

        XCTAssertNil(snapshot.imagePNGData)
        XCTAssertEqual(snapshot.captureStorageRejection, .imageRepresentationInvalid)
    }

    func testImageCaptureRejectsMalformedTIFFWithFormatReason() async throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.setData(Data("not-a-tiff".utf8), forType: .tiff))
        let controller = SystemClipboardPort(pasteboard: pasteboard)

        let readSnapshot = await controller.readSnapshot(
            ifChangeCountIs: pasteboard.changeCount
        )
        let snapshot = try XCTUnwrap(readSnapshot)

        XCTAssertNil(snapshot.imagePNGData)
        XCTAssertEqual(snapshot.captureStorageRejection, .imageRepresentationInvalid)
    }

    func testImageCaptureNormalizesValidTIFFToValidatedPNG() async throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let tiffData = try makeImageData(using: .tiff)
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.setData(tiffData, forType: .tiff))
        let controller = SystemClipboardPort(pasteboard: pasteboard)

        let readSnapshot = await controller.readSnapshot(
            ifChangeCountIs: pasteboard.changeCount
        )
        let snapshot = try XCTUnwrap(readSnapshot)
        let pngData = try XCTUnwrap(snapshot.imagePNGData)

        XCTAssertEqual(NSBitmapImageRep(data: pngData)?.pixelsWide, 2)
        XCTAssertNil(snapshot.captureStorageRejection)
    }

    func testImageCaptureClassifiesDecodedPixelBudgetAsOversized() async throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let pngData = try makeImageData(using: .png, width: 64, height: 64)
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.setData(pngData, forType: .png))
        var limits = SystemClipboardStorageLimits.productDefault
        limits.maximumImageByteCount = pngData.count
        limits.maximumDecodedImageByteCount = max(pngData.count, 4_096)
        let controller = SystemClipboardPort(
            pasteboard: pasteboard,
            storageLimits: limits
        )

        let readSnapshot = await controller.readSnapshot(
            ifChangeCountIs: pasteboard.changeCount
        )
        let snapshot = try XCTUnwrap(readSnapshot)

        XCTAssertNil(snapshot.imagePNGData)
        XCTAssertEqual(snapshot.captureStorageRejection, .itemTooLarge)
    }

    func testImageWorkspaceBudgetKeepsUHD4KWithinDefaultAndRejectsLargerDCI4K() throws {
        let limits = SystemClipboardStorageLimits.productDefault
        let uhd4KByteCount = PasteboardImageBudget.decodedWorkspaceByteCount(
            width: 3_840,
            height: 2_160,
            depthBitsPerSample: 8
        )
        let dci4KByteCount = PasteboardImageBudget.decodedWorkspaceByteCount(
            width: 4_096,
            height: 2_160,
            depthBitsPerSample: 8
        )

        XCTAssertEqual(uhd4KByteCount, 132_710_400)
        XCTAssertLessThanOrEqual(
            try XCTUnwrap(uhd4KByteCount),
            UInt64(limits.maximumDecodedImageByteCount)
        )
        XCTAssertGreaterThan(
            try XCTUnwrap(dci4KByteCount),
            UInt64(limits.maximumDecodedImageByteCount)
        )
        XCTAssertEqual(
            PasteboardImageBudget.decodedWorkspaceByteCount(
                width: 1,
                height: 1,
                depthBitsPerSample: 64
            ),
            32
        )
    }

    func testImageCaptureRejectsHighDepthTIFFAboveConservativeWorkspaceBudget() async throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let width = 64
        let height = 64
        let tiffData = try makeImageData(
            using: .tiff,
            width: width,
            height: height,
            bitsPerSample: 16
        )
        let source = try XCTUnwrap(CGImageSourceCreateWithData(tiffData as CFData, nil))
        let properties = try XCTUnwrap(
            CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any]
        )
        XCTAssertEqual((properties[kCGImagePropertyDepth] as? NSNumber)?.intValue, 16)
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.setData(tiffData, forType: .tiff))
        var limits = SystemClipboardStorageLimits.productDefault
        limits.maximumImageByteCount = tiffData.count
        limits.maximumDecodedImageByteCount = width * height * 16 - 1
        let controller = SystemClipboardPort(
            pasteboard: pasteboard,
            storageLimits: limits
        )

        let readSnapshot = await controller.readSnapshot(
            ifChangeCountIs: pasteboard.changeCount
        )
        let snapshot = try XCTUnwrap(readSnapshot)

        XCTAssertNil(snapshot.imagePNGData)
        XCTAssertEqual(snapshot.captureStorageRejection, .itemTooLarge)
    }

    func testFileCaptureDoesNotReadOrRejectIrrelevantImageRepresentation() async throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let pngData = try makePNGData()
        let fileURL = URL(fileURLWithPath: "/tmp/rill-capacity-file.txt")
        let item = NSPasteboardItem()
        XCTAssertTrue(item.setString(fileURL.absoluteString, forType: .fileURL))
        XCTAssertTrue(item.setData(pngData, forType: .png))
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.writeObjects([item]))
        var limits = SystemClipboardStorageLimits.productDefault
        limits.maximumImageByteCount = 1
        let controller = SystemClipboardPort(
            pasteboard: pasteboard,
            storageLimits: limits
        )

        let readSnapshot = await controller.readSnapshot(
            ifChangeCountIs: pasteboard.changeCount
        )
        let snapshot = try XCTUnwrap(readSnapshot)

        XCTAssertEqual(snapshot.fileURLs, [fileURL])
        XCTAssertNil(snapshot.imagePNGData)
        XCTAssertNil(snapshot.captureStorageRejection)
    }

    func testTemporaryWriteRestoresEveryItemRepresentationAndOrderLosslessly() throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let controller = SystemClipboardPort(pasteboard: pasteboard)
        let firstItem = NSPasteboardItem()
        firstItem.setData(
            Data("{\\rtf1 preserved}".utf8),
            forType: .rtf
        )
        firstItem.setData(
            Data([0x00, 0xFF, 0x10, 0x80]),
            forType: .init("com.example.private-binary")
        )
        firstItem.setString("preserved text", forType: .string)
        let secondItem = NSPasteboardItem()
        secondItem.setData(
            Data([0x25, 0x50, 0x44, 0x46]),
            forType: .pdf
        )
        secondItem.setData(
            Data("second-item".utf8),
            forType: .init("com.example.second-item")
        )
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.writeObjects([firstItem, secondItem]))
        let expectedChangeCount = pasteboard.changeCount
        let expectedContents = rawContents(of: pasteboard)

        let transaction = try controller.beginTemporaryWrite(
            SystemClipboardSnapshot(plainText: "temporary", changeCount: 0),
            ifChangeCountIs: expectedChangeCount
        )

        XCTAssertEqual(pasteboard.string(forType: .string), "temporary")
        XCTAssertTrue(controller.isOwnedChangeCount(transaction.temporaryChangeCount))
        XCTAssertEqual(controller.restore(transaction), .restored)
        XCTAssertEqual(rawContents(of: pasteboard), expectedContents)
    }

    func testTemporaryWriteAcceptsExactRepresentationItemAndTotalByteBoundaries() throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let item = NSPasteboardItem()
        XCTAssertTrue(item.setData(Data(repeating: 0, count: 4), forType: .init("com.example.a")))
        XCTAssertTrue(item.setData(Data(repeating: 1, count: 4), forType: .init("com.example.b")))
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.writeObjects([item]))
        let expectedContents = rawContents(of: pasteboard)
        var limits = preservationLimits()
        limits.maximumRepresentationCountPerItem = 2
        limits.maximumTotalRepresentationCount = 2
        limits.maximumRepresentationByteCount = 4
        limits.maximumItemByteCount = 8
        limits.maximumTotalByteCount = 8
        let controller = SystemClipboardPort(
            pasteboard: pasteboard,
            temporaryPreservationLimits: limits
        )

        let transaction = try controller.beginTemporaryWrite(
            SystemClipboardSnapshot(plainText: "temporary", changeCount: 0),
            ifChangeCountIs: pasteboard.changeCount
        )

        XCTAssertEqual(controller.restore(transaction), .restored)
        XCTAssertEqual(rawContents(of: pasteboard), expectedContents)
    }

    func testTemporaryRestoreNeverOverwritesAnExternalClipboardChange() throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let controller = SystemClipboardPort(pasteboard: pasteboard)
        let expectedChangeCount = controller.writePlainText("preserved")
        let transaction = try controller.beginTemporaryWrite(
            SystemClipboardSnapshot(plainText: "temporary", changeCount: 0),
            ifChangeCountIs: expectedChangeCount
        )
        pasteboard.clearContents()
        pasteboard.setString("external winner", forType: .string)

        XCTAssertEqual(controller.restore(transaction), .skippedChangeCount)
        XCTAssertEqual(pasteboard.string(forType: .string), "external winner")
    }

    func testTemporaryWriteRejectsChangedPasteboardWithoutOverwritingIt() {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let controller = SystemClipboardPort(pasteboard: pasteboard)
        let staleChangeCount = controller.writePlainText("stale")
        _ = controller.writePlainText("external winner")

        XCTAssertThrowsError(
            try controller.beginTemporaryWrite(
                SystemClipboardSnapshot(plainText: "must not win", changeCount: 0),
                ifChangeCountIs: staleChangeCount
            )
        ) { error in
            XCTAssertEqual(
                error as? SystemClipboardPort.ConditionalWriteError,
                .changeCountChanged
            )
        }
        XCTAssertEqual(pasteboard.string(forType: .string), "external winner")
    }

    func testTemporaryWriteRejectsProtectedPasteboardWithoutOverwritingIt() {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let controller = SystemClipboardPort(pasteboard: pasteboard)
        let expectedChangeCount = controller.writeSnapshot(
            SystemClipboardSnapshot(
                plainText: "protected winner",
                changeCount: 0,
                protections: [.concealed]
            )
        )

        XCTAssertThrowsError(
            try controller.beginTemporaryWrite(
                SystemClipboardSnapshot(plainText: "must not win", changeCount: 0),
                ifChangeCountIs: expectedChangeCount
            )
        ) { error in
            XCTAssertEqual(
                error as? SystemClipboardPort.ConditionalWriteError,
                .protectedClipboard([.concealed])
            )
        }
        XCTAssertEqual(pasteboard.string(forType: .string), "protected winner")
    }

    func testTemporaryWriteRejectsAnUnreadableRepresentationBeforeOverwrite() {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let controller = SystemClipboardPort(pasteboard: pasteboard)
        let provider = UnreadablePasteboardDataProvider()
        let item = NSPasteboardItem()
        let promisedType = NSPasteboard.PasteboardType("com.example.unreadable")
        XCTAssertTrue(item.setDataProvider(provider, forTypes: [promisedType]))
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.writeObjects([item]))
        let expectedChangeCount = pasteboard.changeCount

        var observedError: SystemClipboardPort.ConditionalWriteError?
        XCTAssertThrowsError(
            try controller.beginTemporaryWrite(
                SystemClipboardSnapshot(plainText: "must not win", changeCount: 0),
                ifChangeCountIs: expectedChangeCount
            )
        ) { error in
            observedError = error as? SystemClipboardPort.ConditionalWriteError
        }
        switch observedError {
        case .unreadableRepresentation(
            itemIndex: 0,
            typeName: promisedType.rawValue
        ):
            XCTAssertEqual(pasteboard.changeCount, expectedChangeCount)
        case .changeCountChanged:
            // Under load, macOS may invalidate an unresolved promised
            // representation while it is being materialized. That advances
            // the named pasteboard's change count before Rill can report the
            // more specific unreadable-representation error. Both outcomes
            // are fail-closed and must leave the replacement unwritten.
            XCTAssertNotEqual(pasteboard.changeCount, expectedChangeCount)
        default:
            XCTFail("Unexpected conditional write error: \(String(describing: observedError))")
        }
        XCTAssertNil(pasteboard.string(forType: .string))
        withExtendedLifetime(provider) {}
    }

    func testTemporaryWriteRejectsPasteboardItemCountOverBudgetBeforeOverwrite() {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let items = (0..<2).map { index in
            pasteboardItem(typeName: "com.example.item-\(index)", byteCount: 1)
        }
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.writeObjects(items))
        var limits = preservationLimits()
        limits.maximumItemCount = 1

        assertTemporaryWriteRejected(
            on: pasteboard,
            limits: limits,
            expectedLimit: .itemCount
        )
    }

    func testTemporaryWriteRejectsRepresentationsPerItemOverBudgetBeforeReadingData() {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let item = NSPasteboardItem()
        XCTAssertTrue(item.setData(Data([0]), forType: .init("com.example.first")))
        XCTAssertTrue(item.setData(Data([1]), forType: .init("com.example.second")))
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.writeObjects([item]))
        var limits = preservationLimits()
        limits.maximumRepresentationCountPerItem = 1

        assertTemporaryWriteRejected(
            on: pasteboard,
            limits: limits,
            expectedLimit: .representationsPerItem
        )
    }

    func testTemporaryWriteRejectsTotalRepresentationCountOverBudget() {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let items = (0..<2).map { index in
            pasteboardItem(typeName: "com.example.total-\(index)", byteCount: 1)
        }
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.writeObjects(items))
        var limits = preservationLimits()
        limits.maximumRepresentationCountPerItem = 1
        limits.maximumTotalRepresentationCount = 1

        assertTemporaryWriteRejected(
            on: pasteboard,
            limits: limits,
            expectedLimit: .totalRepresentationCount
        )
    }

    func testTemporaryWriteRejectsOverlongRepresentationTypeName() {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let item = pasteboardItem(
            typeName: "com.example.private-type-name",
            byteCount: 1
        )
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.writeObjects([item]))
        var limits = preservationLimits()
        limits.maximumTypeNameUTF8ByteCount = 8

        assertTemporaryWriteRejected(
            on: pasteboard,
            limits: limits,
            expectedLimit: .typeNameByteCount
        )
    }

    func testTemporaryWriteRejectsSingleRepresentationByteBudget() {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let item = pasteboardItem(typeName: "com.example.large-pdf", byteCount: 5)
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.writeObjects([item]))
        var limits = preservationLimits()
        limits.maximumRepresentationByteCount = 4

        assertTemporaryWriteRejected(
            on: pasteboard,
            limits: limits,
            expectedLimit: .representationByteCount
        )
    }

    func testTemporaryWriteRejectsPerItemAggregateByteBudget() {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let item = NSPasteboardItem()
        XCTAssertTrue(item.setData(Data(repeating: 0, count: 4), forType: .init("com.example.a")))
        XCTAssertTrue(item.setData(Data(repeating: 1, count: 4), forType: .init("com.example.b")))
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.writeObjects([item]))
        var limits = preservationLimits()
        limits.maximumRepresentationByteCount = 4
        limits.maximumItemByteCount = 7

        assertTemporaryWriteRejected(
            on: pasteboard,
            limits: limits,
            expectedLimit: .itemByteCount
        )
    }

    func testTemporaryWriteRejectsTotalAggregateByteBudget() {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let items = (0..<2).map { index in
            pasteboardItem(typeName: "com.example.aggregate-\(index)", byteCount: 4)
        }
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.writeObjects(items))
        var limits = preservationLimits()
        limits.maximumRepresentationByteCount = 4
        limits.maximumItemByteCount = 4
        limits.maximumTotalByteCount = 7

        assertTemporaryWriteRejected(
            on: pasteboard,
            limits: limits,
            expectedLimit: .totalByteCount
        )
    }

    func testOversizedPrivateMetadataIsIgnoredWithoutDecodingTagsOrOwnership() {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        var limits = preservationLimits()
        limits.maximumMetadataByteCount = 32
        let controller = SystemClipboardPort(
            pasteboard: pasteboard,
            temporaryPreservationLimits: limits
        )
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.setString("ordinary", forType: .string))
        XCTAssertTrue(pasteboard.setData(
            Data(repeating: 0x41, count: 33),
            forType: .init("dev.rill.metadata")
        ))
        let changeCount = pasteboard.changeCount

        XCTAssertTrue(controller.currentDescriptor().captureTags.isEmpty)
        XCTAssertFalse(controller.isOwnedChangeCount(changeCount))
    }

    func testPrivateMetadataOverTagCountBudgetIsIgnored() {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        var limits = preservationLimits()
        limits.maximumMetadataCaptureTagCount = 1
        let controller = SystemClipboardPort(
            pasteboard: pasteboard,
            temporaryPreservationLimits: limits
        )
        let metadata = Data(
            #"{"captureTags":["exclude-from-workflow-capture","polish-generated"],"writerInstanceID":null}"#.utf8
        )
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.setData(
            metadata,
            forType: .init("dev.rill.metadata")
        ))

        XCTAssertTrue(controller.currentDescriptor().captureTags.isEmpty)
    }

    func testWrittenPrivateMetadataCapsCaptureTagCountAndRetainsOwnershipMarker() {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        var limits = preservationLimits()
        limits.maximumMetadataCaptureTagCount = 1
        let controller = SystemClipboardPort(
            pasteboard: pasteboard,
            temporaryPreservationLimits: limits
        )

        let changeCount = controller.writeSnapshot(
            SystemClipboardSnapshot(
                plainText: "bounded metadata",
                changeCount: 0,
                captureTags: [.excludeFromWorkflowCapture, .polishGenerated]
            )
        )

        XCTAssertEqual(
            controller.currentDescriptor().captureTags,
            [.excludeFromWorkflowCapture]
        )
        XCTAssertTrue(controller.isOwnedChangeCount(changeCount))
    }

    private func rawContents(of pasteboard: NSPasteboard) -> [RawPasteboardItem] {
        (pasteboard.pasteboardItems ?? []).map { item in
            RawPasteboardItem(
                representations: item.types.map { type in
                    RawPasteboardRepresentation(
                        typeName: type.rawValue,
                        data: item.data(forType: type)
                    )
                }
            )
        }
    }

    private func assertTemporaryWriteRejected(
        on pasteboard: NSPasteboard,
        limits: SystemClipboardPort.TemporaryPreservationLimits,
        expectedLimit: SystemClipboardPort.TemporaryPreservationLimit,
        file: StaticString = #filePath,
        line: UInt = #line
    ) {
        let controller = SystemClipboardPort(
            pasteboard: pasteboard,
            temporaryPreservationLimits: limits
        )
        let expectedChangeCount = pasteboard.changeCount

        XCTAssertThrowsError(
            try controller.beginTemporaryWrite(
                SystemClipboardSnapshot(plainText: "must not win", changeCount: 0),
                ifChangeCountIs: expectedChangeCount
            ),
            file: file,
            line: line
        ) { error in
            XCTAssertEqual(
                error as? SystemClipboardPort.ConditionalWriteError,
                .preservationLimitExceeded(expectedLimit),
                file: file,
                line: line
            )
        }
        XCTAssertEqual(pasteboard.changeCount, expectedChangeCount, file: file, line: line)
        XCTAssertNil(pasteboard.string(forType: .string), file: file, line: line)
    }

    private func pasteboardItem(typeName: String, byteCount: Int) -> NSPasteboardItem {
        let item = NSPasteboardItem()
        XCTAssertTrue(item.setData(
            Data(repeating: 0x41, count: byteCount),
            forType: .init(typeName)
        ))
        return item
    }

    private func preservationLimits() -> SystemClipboardPort.TemporaryPreservationLimits {
        SystemClipboardPort.TemporaryPreservationLimits(
            maximumItemCount: 8,
            maximumRepresentationCountPerItem: 4,
            maximumTotalRepresentationCount: 16,
            maximumTypeNameUTF8ByteCount: 128,
            maximumRepresentationByteCount: 8,
            maximumItemByteCount: 16,
            maximumTotalByteCount: 32,
            maximumMetadataByteCount: 4_096,
            maximumMetadataCaptureTagCount: 4
        )
    }

    private func makePNGData() throws -> Data {
        try makeImageData(using: .png)
    }

    private func makeImageData(
        using fileType: NSBitmapImageRep.FileType,
        width: Int = 2,
        height: Int = 2,
        bitsPerSample: Int = 8
    ) throws -> Data {
        let representation = try XCTUnwrap(
            NSBitmapImageRep(
                bitmapDataPlanes: nil,
                pixelsWide: width,
                pixelsHigh: height,
                bitsPerSample: bitsPerSample,
                samplesPerPixel: 4,
                hasAlpha: true,
                isPlanar: false,
                colorSpaceName: .deviceRGB,
                bytesPerRow: 0,
                bitsPerPixel: 0
            )
        )
        return try XCTUnwrap(representation.representation(using: fileType, properties: [:]))
    }
}

private struct RawPasteboardItem: Equatable {
    let representations: [RawPasteboardRepresentation]
}

private struct RawPasteboardRepresentation: Equatable {
    let typeName: String
    let data: Data?
}

private final class UnreadablePasteboardDataProvider: NSObject, NSPasteboardItemDataProvider {
    nonisolated func pasteboard(
        _ pasteboard: NSPasteboard?,
        item: NSPasteboardItem,
        provideDataForType type: NSPasteboard.PasteboardType
    ) {
        // Intentionally leave the promise unresolved. Temporary transactions
        // must fail closed rather than replace data they cannot restore.
    }
}

private actor PasteboardImageWorkerGate {
    struct Statistics: Sendable {
        let invocationCount: Int
        let maximumConcurrentWorkerCount: Int
    }

    private var invocationCount = 0
    private var activeWorkerCount = 0
    private var maximumConcurrentWorkerCount = 0
    private var releasePermitCount = 0
    private var releasesAllWorkers = false
    private var workerContinuations: [CheckedContinuation<Void, Never>] = []
    private var invocationWaiters: [(
        count: Int,
        continuation: CheckedContinuation<Void, Never>
    )] = []

    func blockWorker() async {
        invocationCount += 1
        activeWorkerCount += 1
        maximumConcurrentWorkerCount = max(
            maximumConcurrentWorkerCount,
            activeWorkerCount
        )
        resumeSatisfiedInvocationWaiters()

        if releasesAllWorkers {
            activeWorkerCount -= 1
            return
        }
        if releasePermitCount > 0 {
            releasePermitCount -= 1
            activeWorkerCount -= 1
            return
        }
        await withCheckedContinuation { continuation in
            workerContinuations.append(continuation)
        }
        activeWorkerCount -= 1
    }

    func waitUntilBlocked() async {
        await waitUntilInvocationCount(1)
    }

    func waitUntilInvocationCount(_ count: Int) async {
        guard invocationCount < count else { return }
        await withCheckedContinuation { continuation in
            invocationWaiters.append((count, continuation))
        }
    }

    func releaseWorker() {
        releaseNextWorker()
    }

    func releaseNextWorker() {
        guard !workerContinuations.isEmpty else {
            releasePermitCount += 1
            return
        }
        workerContinuations.removeFirst().resume()
    }

    func releaseAllWorkers() {
        releasesAllWorkers = true
        let continuations = workerContinuations
        workerContinuations.removeAll()
        continuations.forEach { $0.resume() }
    }

    func statistics() -> Statistics {
        Statistics(
            invocationCount: invocationCount,
            maximumConcurrentWorkerCount: maximumConcurrentWorkerCount
        )
    }

    private func resumeSatisfiedInvocationWaiters() {
        var pending: [(
            count: Int,
            continuation: CheckedContinuation<Void, Never>
        )] = []
        for waiter in invocationWaiters {
            if invocationCount >= waiter.count {
                waiter.continuation.resume()
            } else {
                pending.append(waiter)
            }
        }
        invocationWaiters = pending
    }
}
