config_version: '1'
schema_list:
  - schema: rill_pinyin
menu:
  page_size: 6
ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Shift_L: inline_ascii
    Shift_R: inline_ascii
    Control_L: noop
    Control_R: noop
    Caps_Lock: clear
