// Generated by scripts/generate_builtin_workflows.py from
// Sources/RillApp/Resources/BuiltinWorkflows.toml. Do not edit.

import Foundation
import RillCore

private func staticUUID(_ string: String) -> UUID {
    guard let uuid = UUID(uuidString: string) else {
        preconditionFailure("Invalid UUID string: \(string)")
    }
    return uuid
}

public struct BuiltinWorkflowCatalog: WorkflowCatalog {
    public init() {}

    public func manifest() -> WorkflowManifest {
        WorkflowManifest(
            schemaVersion: 1,
            workflows: [
                WorkflowDefinition(
                    id: staticUUID("B9E19A88-F9FB-4AB3-8444-CDBF7E215A88"),
                    name: "Accurate Transcription",
                    titleKey: .pushToTalkCapture,
                    trigger: .hotkey,
                    pipeline: PipelineDeclaration(
                        recognizerID: "sherpa-onnx.local",
                        postProcessSteps: [
                            PostProcessStep(
                                id: staticUUID("3e1b7747-b5d3-5ed4-8e32-465c404ebacb"),
                                kind: .normalizeWhitespace
                            ),
                        ],
                        outputActions: [
                            OutputActionReference(id: "inject.text"),
                        ],
                        uncertaintyPolicy: UncertaintyPolicy(
                            mode: .off,
                            confidenceThreshold: 0,
                            timeoutSeconds: 0
                        ),
                        deliveryPolicy: DeliveryPolicy(strategy: .immediate)
                    ),
                    ui: WorkflowUIConfig(
                        symbolName: "mic.fill",
                        accentColorName: "red"
                    ),
                    metadata: [
                        "catalog": "builtin",
                        "workflow.speech-mode": "dedicated-transcription",
                        "trigger.gesture": "fn-hold",
                        "interaction.mode": "press-and-hold",
                        "workflow.builtin-kind": "push-to-talk.dictation",
                        "workflow.exclusive-group": "builtin.push-to-talk",
                        "settings.expose.output-mode": "true",
                        "workflow.text-style": "cleanInput",
                    ]
                ),
                WorkflowDefinition(
                    id: staticUUID("A8E19A88-F9FB-4AB3-8444-CDBF7E215A88"),
                    name: "Streaming Direct",
                    titleKey: .streamingInput,
                    trigger: .hotkey,
                    pipeline: PipelineDeclaration(
                        recognizerID: "sherpa-onnx.streaming",
                        postProcessSteps: [],
                        outputActions: [
                            OutputActionReference(id: "inject.text"),
                        ],
                        uncertaintyPolicy: UncertaintyPolicy(
                            mode: .off,
                            confidenceThreshold: 0,
                            timeoutSeconds: 0
                        ),
                        deliveryPolicy: DeliveryPolicy(strategy: .immediate)
                    ),
                    ui: WorkflowUIConfig(
                        symbolName: "waveform.badge.mic",
                        accentColorName: "orange"
                    ),
                    metadata: [
                        "catalog": "builtin",
                        "workflow.speech-mode": "streaming-direct",
                        "trigger.gesture": "fn-hold",
                        "interaction.mode": "press-and-hold",
                        "workflow.builtin-kind": "push-to-talk.streaming",
                        "workflow.exclusive-group": "builtin.push-to-talk",
                        "settings.expose.output-mode": "true",
                        "workflow.text-style": "rawInput",
                    ]
                ),
                WorkflowDefinition(
                    id: staticUUID("D1E19A88-F9FB-4AB3-8444-CDBF7E215A88"),
                    name: "Transcription + LLM Rewrite",
                    titleKey: .pushToTalkPolish,
                    trigger: .hotkey,
                    pipeline: PipelineDeclaration(
                        recognizerID: "sherpa-onnx.local",
                        postProcessSteps: [
                            PostProcessStep(
                                id: staticUUID("08d55045-9627-56bd-a7be-713ccee5994b"),
                                kind: .normalizeWhitespace
                            ),
                            PostProcessStep(
                                id: staticUUID("b60be670-c8bd-5196-996c-55c22a758702"),
                                kind: .llmRewrite,
                                prompt: "Polish into a concise final message while preserving meaning and language."
                            ),
                        ],
                        outputActions: [
                            OutputActionReference(id: "inject.text"),
                        ],
                        uncertaintyPolicy: UncertaintyPolicy(
                            mode: .off,
                            confidenceThreshold: 0,
                            timeoutSeconds: 0
                        ),
                        deliveryPolicy: DeliveryPolicy(strategy: .immediate)
                    ),
                    ui: WorkflowUIConfig(
                        symbolName: "wand.and.stars",
                        accentColorName: "purple"
                    ),
                    metadata: [
                        "catalog": "builtin",
                        "workflow.availability": "planned",
                        "workflow.speech-mode": "transcription-with-rewrite",
                        "trigger.gesture": "fn-hold",
                        "interaction.mode": "press-and-hold",
                        "workflow.builtin-kind": "push-to-talk.polish",
                        "workflow.exclusive-group": "builtin.push-to-talk",
                        "settings.expose.output-mode": "true",
                        "workflow.text-style": "formalWriting",
                    ]
                ),
                WorkflowDefinition(
                    id: staticUUID("C0E19A88-F9FB-4AB3-8444-CDBF7E215A88"),
                    name: "Raw Input",
                    titleKey: .rawInput,
                    trigger: .manual,
                    pipeline: PipelineDeclaration(
                        recognizerID: "sherpa-onnx.local",
                        postProcessSteps: [],
                        outputActions: [
                            OutputActionReference(id: "stack.push"),
                        ],
                        uncertaintyPolicy: UncertaintyPolicy(
                            mode: .off,
                            confidenceThreshold: 0,
                            timeoutSeconds: 0
                        ),
                        deliveryPolicy: DeliveryPolicy(strategy: .stackFirst)
                    ),
                    ui: WorkflowUIConfig(
                        symbolName: "text.quote",
                        accentColorName: "gray"
                    ),
                    metadata: [
                        "catalog": "builtin",
                        "workflow.builtin-kind": "voice-mode.raw",
                        "recognizer.selection": "auto",
                        "workflow.text-style": "rawInput",
                    ]
                ),
            ],
            metadata: [
                "source": "builtin",
                "format": "toml",
            ]
        )
    }
}
