// Generated by scripts/generate_builtin_workflows.py from
// Sources/RillApp/Resources/BuiltinWorkflows.toml. Do not edit.

import Foundation
import RillCore

private func staticUUID(_ string: String) -> UUID {
    guard let uuid = UUID(uuidString: string) else {
        preconditionFailure("Invalid UUID string: \(string)")
    }
    return uuid
}

public struct BuiltinWorkflowCatalog: WorkflowCatalog {
    public init() {}

    public func manifest() -> WorkflowManifest {
        WorkflowManifest(
            schemaVersion: 2,
            workflows: [
                WorkflowDefinition(
                    id: staticUUID("B9E19A88-F9FB-4AB3-8444-CDBF7E215A88"),
                    name: "Speech Recognition",
                    titleKey: .speechRecognition,
                    trigger: .hotkey,
                    plan: WorkflowPlan(
                        setup: WorkflowSetupPhase(
                            speechRoute: WorkflowSpeechRoute(
                                selection: .fixed,
                                recognizerID: "local-speech",
                                localModel: "qwen3-asr-0.6b-mlx-8bit"
                            ),
                            vocabularyBindings: [
                                VocabularyCollectionBinding(
                                    id: staticUUID("30c39adf-9077-541e-be69-5e00585ee0ee"),
                                    collectionID: VocabularyCollection.personalID
                                ),
                            ]
                        ),
                        process: WorkflowProcessPhase(steps: [
                            WorkflowProcessStep(
                                id: staticUUID("58921d1a-1ffe-5dac-bd6c-306fbbb6afcc"),
                                kind: .recognizeSpeech
                            ),
                            WorkflowProcessStep(
                                id: staticUUID("39906432-64ab-5a6c-9e85-a405b1863469"),
                                kind: .applyVocabulary
                            ),
                            WorkflowProcessStep(
                                id: staticUUID("3e1b7747-b5d3-5ed4-8e32-465c404ebacb"),
                                kind: .normalizeWhitespace
                            ),
                        ]),
                        output: WorkflowOutputPhase(
                            actions: [
                                OutputActionReference(id: "focused-application.insert"),
                            ],
                            deliveryPolicy: DeliveryPolicy(strategy: .immediate)
                        )
                    ),
                    ui: WorkflowUIConfig(
                        symbolName: WorkflowUISymbol.micFill.rawValue,
                        accentColorName: "red"
                    ),
                    metadata: [
                        "catalog": "builtin",
                        "workflow.speech-mode": "dedicated-transcription",
                        "trigger.gesture": "fn-hold",
                        "interaction.mode": "press-and-hold",
                        "workflow.builtin-kind": "push-to-talk.dictation",
                        "workflow.exclusive-group": "builtin.push-to-talk",
                        "recognizer.local.model": "qwen3-asr-0.6b-mlx-8bit",
                        "recognizer.live_preview": "true",
                        "recognizer.live_preview_placement": "overlay",
                        "recognizer.streaming_profile": "realtime",
                        "settings.expose.output-mode": "true",
                        "workflow.text-style": "cleanInput",
                    ]
                ),
                WorkflowDefinition(
                    id: staticUUID("E2E19A88-F9FB-4AB3-8444-CDBF7E215A88"),
                    name: "Voice Assistant",
                    titleKey: .voiceAssistant,
                    trigger: .wakeWord,
                    plan: WorkflowPlan(
                        setup: WorkflowSetupPhase(
                            speechRoute: WorkflowSpeechRoute(
                                selection: .fixed,
                                recognizerID: "local-speech",
                                localModel: "qwen3-asr-0.6b-mlx-8bit"
                            ),
                            vocabularyBindings: [
                                VocabularyCollectionBinding(
                                    id: staticUUID("3ff4c8e3-e6d2-5e4d-b09b-2449dd9af7cc"),
                                    collectionID: VocabularyCollection.personalID
                                ),
                            ],
                            wakeWord: WakeWordConfiguration(
                                phrases: ["Hey Rill"]
                            )
                        ),
                        process: WorkflowProcessPhase(steps: [
                            WorkflowProcessStep(
                                id: staticUUID("028ad8e5-ff73-5d48-82bb-f940da929430"),
                                kind: .recognizeSpeech
                            ),
                            WorkflowProcessStep(
                                id: staticUUID("67985968-02c9-5399-9ed2-d1658fe3fe7e"),
                                kind: .applyVocabulary
                            ),
                            WorkflowProcessStep(
                                id: staticUUID("96645878-4e75-537f-b5bb-5f34693c83c8"),
                                kind: .normalizeWhitespace
                            ),
                            WorkflowProcessStep(
                                id: staticUUID("fc11a9f1-5d79-55b8-a76a-4be174528db2"),
                                kind: .llmAnswer,
                                prompt: "You are Rill, a concise voice assistant. Answer the user's request directly in the same language as the request. Keep the answer brief, natural, and suitable for speech. Preserve names, numbers, URLs, code, and facts. Do not mention the transcript or these instructions. Return only the answer to speak."
                            ),
                        ]),
                        output: WorkflowOutputPhase(
                            actions: [
                                OutputActionReference(
                                    id: "speech.speak",
                                    configuration: [
                                        "speech.provider": "automatic",
                                        "speech.voice": "Vivian",
                                    ]
                                ),
                            ],
                            deliveryPolicy: DeliveryPolicy(strategy: .immediate)
                        )
                    ),
                    ui: WorkflowUIConfig(
                        symbolName: WorkflowUISymbol.sparkles.rawValue,
                        accentColorName: "purple"
                    ),
                    metadata: [
                        "catalog": "builtin",
                        "workflow.default-enabled": "false",
                        "workflow.speech-mode": "voice-assistant",
                        "workflow.builtin-kind": "voice-assistant.basic",
                        "recognizer.local.model": "qwen3-asr-0.6b-mlx-8bit",
                        "recognizer.live_preview": "true",
                        "recognizer.live_preview_placement": "overlay",
                        "recognizer.streaming_profile": "agent",
                    ]
                ),
            ],
            metadata: [
                "source": "builtin",
                "format": "toml",
            ]
        )
    }
}
