import RillCore

public enum SurfaceText: String, CaseIterable, Sendable {
  case panelContent
  case collections
  case drafts
  case keepOpen
  case keepThePanelExpandedWhen
  case collapseToPendingStrip
  case closePanel
  case closePendingStrip
  case editsNeedAttention
  case outputNeedsConfirmation
  case nothingPending
  case processing
  case deliveredStateNotSaved
  case checkTheTargetBeforeConfirming
  case retrySave
  case inserted
  case retryItem
  case draftsArea
  case newItem
  case finishRecording
  case recordNewItem
  case removeThisPendingItem
  case remove
  case cancel
  case draftEditsWillBeDiscarded
  case collectVoiceInDrafts
  case whenOffFnDictationTypes
  case collectClipboardInDrafts
  case collectsNewCopiesAfterEnabling
  case opensAutomaticallyIncludingAfterRestart
  case recognizing
  case resultToReview
  case edited
  case inProgress
  case disabledSuffix
  case createADraftOrCollect
  case editText
  case saving
  case unsaved
  case saved
  case dictateHere
  case pendingText
  case selectAnItem
  case editSelectAndUndoText
  case speechResultsAreReadyTo
  case insertAtSelection
  case dismiss
  case reviewChanges
  case compareWith
  case recognition
  case initialDraft
  case deletionsAreStruckThroughAdditions
  case saveAsNewDraft
  case sendTo
  case focusTheTargetAndUse
  case hide
  case sendSelected
  case returnSendsWhileEditingReturn
  case speech
  case clipboard
  case emptyDraft
  case stack
  case queue
  case reusable
  case theDraftExceedsTheLocal
  case enterSomeTextBeforeSending
  case couldNotLoadItemsReopen
  case editsAreNotSavedRetry
  case theItemChangedYourEdits
  case couldNotStartRecordingCheck
  case outputNext
  case remainingCount
  case processingStatus
  case nothingToOutput
  case confirmTheResult
  case advanceOnlyAfterConfirmingInsertion
  case deliveredSettlementPending
  case retrySaving
  case openDrafts
  case focusTheTargetAndPress
  case close
  case empty
  case addTo
  case newSet
  case reusableItems
  case manageOutputBuffers
  case noItems
  case contextCorrectionMemory
  case speechRemainsTheOnlyContent
  case useVocabularyForSmartCleanup
  case applicableHotwordsAreSharedWith
  case screenContext
  case longTermMemoryIdleOrganization
  case screenRecordingPermissionIsUnavailable
  case authorizeCurrentProvider
  case manageMemories
  case organizeWhenIdle
  case backgroundRequestsToday
  case foregroundSummaryRequestsTodayMain
  case authorizeContextProcessing
  case enableForTheseVoiceWorkflows
  case smartCleanupSendsItsApplicable
  case theCurrentLlmReceivesThe
  case theCurrentLlmReceivesAuthorized
  case providerChangesRequireReauthorization
  case userStatement
  case explicitCorrection
  case screenObservation
  case needsConfirmation
  case active
  case archived
  case longTermMemories
  case refresh
  case done
  case sources
  case historyDeletedSuffix
  case proposedReplacement
  case edit
  case confirmed
  case confirm
  case unlock
  case lock
  case restore
  case archive
  case delete
  case permanentlyDeleteThisMemoryAnd
  case deletePermanently
  case correctionReferences
  case preRecordingImage
  case imageSummary
  case memorySummary
  case vocabulary
  case applicable
  case included
  case omittedByBudget
  case sentReferencesAreEvidenceOffered
  case screenObservationNotAPersonal
  case thisSummaryArrivedAfterInputs
  case relatedMemories
  case off
  case unavailableSkipped
  case timedOutSkipped
  case failedSkipped
  case notReadyAtFreezeOmitted
  case prepared
  case sentAsReference
  case requestFailedDeliveryUnconfirmed
  case cancelled
  case outputNextShortcut
  case shortcutConflictChangeOneBinding
  case clipboardPanel
  case theLegacyWorkflowLibraryHas
  case duplicateNameSuffix
  case newWorkflow
  case theWorkflowCouldNotFinish
  case termsCommaSeparated
  case setExpiry
  case archiveAfter
  case saveConfirm
  case speechTextSentReferencesListed
  case currentSpeechModel
  case modelDetailsAndResidency
  case modelId
  case collection
  case allRecords
  case addToDrafts
  case shortcutConflictsWithOutputNext
  case shortcutConflictsWithTheClipboard
  case setUpLater
  case finishSetup
  case forDeepseekUseHttpsApi
  case rillOutputNext
}

extension L10n {
  public static func surface(_ key: SurfaceText, language: AppLanguage) -> String {
    catalogString("surface.\(key.rawValue)", language: language)
  }
}
