import Foundation

public enum ClipboardCaptureTag: String, Codable, Sendable, Equatable, Hashable, CaseIterable {
    case excludeFromWorkflowCapture = "exclude-from-workflow-capture"
    case polishGenerated = "polish-generated"
}

public enum ClipboardProtection: String, Codable, Sendable, Equatable, CaseIterable {
    case concealed
    case transient
    case autoGenerated
}

public struct ClipboardSnapshot: Codable, Sendable, Equatable {
    public var plainText: String
    public var imagePNGData: Data?
    public var fileURLs: [URL]
    public var changeCount: Int
    public var captureTags: [ClipboardCaptureTag]
    public var protections: [ClipboardProtection]
    public var captureStorageRejection: ClipboardStorageRejectionReason?

    private enum CodingKeys: String, CodingKey {
        case plainText
        case imagePNGData
        case fileURLs
        case changeCount
        case captureTags
        case protections
        case captureStorageRejection
    }

    public init(
        plainText: String,
        imagePNGData: Data? = nil,
        fileURLs: [URL] = [],
        changeCount: Int,
        captureTags: [ClipboardCaptureTag] = [],
        protections: [ClipboardProtection] = [],
        captureStorageRejection: ClipboardStorageRejectionReason? = nil
    ) {
        self.plainText = plainText
        self.imagePNGData = imagePNGData
        self.fileURLs = fileURLs
        self.changeCount = changeCount
        self.captureTags = captureTags
        self.protections = protections
        self.captureStorageRejection = captureStorageRejection
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        plainText = try container.decode(String.self, forKey: .plainText)
        imagePNGData = try container.decodeIfPresent(Data.self, forKey: .imagePNGData)
        fileURLs = try container.decodeIfPresent([URL].self, forKey: .fileURLs) ?? []
        changeCount = try container.decode(Int.self, forKey: .changeCount)
        captureTags = try container.decodeIfPresent([ClipboardCaptureTag].self, forKey: .captureTags) ?? []
        protections = try container.decodeIfPresent([ClipboardProtection].self, forKey: .protections) ?? []
        captureStorageRejection = try container.decodeIfPresent(
            ClipboardStorageRejectionReason.self,
            forKey: .captureStorageRejection
        )
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(plainText, forKey: .plainText)
        try container.encodeIfPresent(imagePNGData, forKey: .imagePNGData)
        try container.encode(fileURLs, forKey: .fileURLs)
        try container.encode(changeCount, forKey: .changeCount)
        try container.encode(captureTags, forKey: .captureTags)
        try container.encode(protections, forKey: .protections)
        try container.encodeIfPresent(captureStorageRejection, forKey: .captureStorageRejection)
    }
}

public struct ClipboardDescriptor: Sendable, Equatable {
    public var hasPlainText: Bool
    public var hasImage: Bool
    public var hasFiles: Bool
    public var changeCount: Int
    public var captureTags: [ClipboardCaptureTag]
    public var protections: [ClipboardProtection]

    public init(
        hasPlainText: Bool,
        hasImage: Bool,
        hasFiles: Bool,
        changeCount: Int,
        captureTags: [ClipboardCaptureTag] = [],
        protections: [ClipboardProtection] = []
    ) {
        self.hasPlainText = hasPlainText
        self.hasImage = hasImage
        self.hasFiles = hasFiles
        self.changeCount = changeCount
        self.captureTags = captureTags
        self.protections = protections
    }

    public init(snapshot: ClipboardSnapshot) {
        self.init(
            hasPlainText: !snapshot.plainText.isEmpty,
            hasImage: snapshot.imagePNGData != nil,
            hasFiles: !snapshot.fileURLs.isEmpty,
            changeCount: snapshot.changeCount,
            captureTags: snapshot.captureTags,
            protections: snapshot.protections
        )
    }

    public var hasTransferableContent: Bool {
        hasPlainText || hasImage || hasFiles
    }

    public var policySnapshot: ClipboardSnapshot {
        ClipboardSnapshot(
            plainText: "",
            changeCount: changeCount,
            captureTags: captureTags,
            protections: protections
        )
    }
}

public struct FocusSnapshot: Codable, Sendable, Equatable {
    public var applicationName: String?
    public var bundleIdentifier: String?
    public var processIdentifier: Int32?
    public var focusedRole: String?
    public var selectedText: String
    public var secureInput: Bool
    public var capturedAt: Date

    public init(
        applicationName: String?,
        bundleIdentifier: String?,
        processIdentifier: Int32?,
        focusedRole: String?,
        selectedText: String,
        secureInput: Bool,
        capturedAt: Date = Date()
    ) {
        self.applicationName = applicationName
        self.bundleIdentifier = bundleIdentifier
        self.processIdentifier = processIdentifier
        self.focusedRole = focusedRole
        self.selectedText = selectedText
        self.secureInput = secureInput
        self.capturedAt = capturedAt
    }
}

public struct ContextSnapshot: Codable, Sendable, Equatable {
    public var focus: FocusSnapshot
    public var clipboard: ClipboardSnapshot

    public init(focus: FocusSnapshot, clipboard: ClipboardSnapshot) {
        self.focus = focus
        self.clipboard = clipboard
    }
}

public extension ContextSnapshot {
    static let empty = ContextSnapshot(
        focus: FocusSnapshot(
            applicationName: nil,
            bundleIdentifier: nil,
            processIdentifier: nil,
            focusedRole: nil,
            selectedText: "",
            secureInput: false
        ),
        clipboard: ClipboardSnapshot(plainText: "", changeCount: 0)
    )
}

public extension ClipboardSnapshot {
    var hasTransferableContent: Bool {
        !plainText.isEmpty || imagePNGData?.isEmpty == false || !fileURLs.isEmpty
    }

    func hasEquivalentTransferableContent(as other: ClipboardSnapshot) -> Bool {
        plainText == other.plainText
            && imagePNGData == other.imagePNGData
            && fileURLs == other.fileURLs
            && Set(captureTags) == Set(other.captureTags)
            && Set(protections) == Set(other.protections)
    }

    var excludesWorkflowCapture: Bool {
        captureTags.contains(.excludeFromWorkflowCapture)
    }

    func appendingCaptureTags(_ tags: [ClipboardCaptureTag]) -> ClipboardSnapshot {
        var snapshot = self
        for tag in tags where !snapshot.captureTags.contains(tag) {
            snapshot.captureTags.append(tag)
        }
        return snapshot
    }

    func removingCaptureTags(_ tags: [ClipboardCaptureTag]) -> ClipboardSnapshot {
        var snapshot = self
        snapshot.captureTags.removeAll(where: { tags.contains($0) })
        return snapshot
    }
}
