import Foundation

/// Removes user content and secrets before a diagnostic event crosses a storage or publication boundary.
public enum DiagnosticEventSanitizer {
  public static let invalidEventCode = "diagnostic.event.invalid"
  public static let sanitizedMessage = "Diagnostic event recorded."

  private enum MetadataValueKind {
    case boolean
    case closed(Set<String>)
    case closedList(Set<String>)
    case count
    case eventCode
    case integer
  }

  /// Event names are a protocol, not an extensible text field. New producers
  /// must add their coordinate here before it can cross a persistence or copy
  /// boundary. Unknown-but-well-formed strings deliberately fail closed.
  private static let eventCodeCatalog = Set(DiagnosticEventName.allCases.map(\.rawValue))

  private static let actionIDs: Set<String> = [
    // Persisted workflow receipts can still contain pre-Record identifiers.
    "clipboard.copy",
    "inject.text",
    "stack.push",
    "system-clipboard.copy",
    "external.markdown.append",
    "external.shortcuts.run",
    "external.webhook.post",
    "focused-application.insert",
    "record.store",

    // Package-owned fixture components used to verify typed coordinates.
    "group.stack.action",
    "probe.action",
  ]

  private static let recognizerIDs: Set<String> = [
    "local-speech",
    "context.selection",
    "sherpa-onnx.local",
    "sherpa-onnx.streaming",
    "mock.recognizer",
  ]

  private static let transformerIDs: Set<String> = [
    "transformer.openai.responses.rewrite",
    "transformer.normalize",
    "mock.transformer",
  ]

  private static let providerIDs: Set<String> = [
    "local-speech",
    "openai.responses",
    "llm.responses",
    "sherpa-onnx.local",
    "sherpa-onnx.streaming",
    "whisperkit.stream",
  ]

  private static let providerKinds: Set<String> = [
    "mlx-audio-swift",
    "openai",
    "llm",
    "sherpa-onnx",
    "whisperkit",
    "whisperkit.live",
  ]

  private static let providerModels: Set<String> = [
    "qwen3-asr-0.6b-mlx-8bit", "qwen3-asr-1.7b-mlx-8bit",
    "qwen3-tts-0.6b-customvoice-mlx-4bit",
    "qwen3-tts-0.6b-customvoice-mlx-8bit",
    "qwen3-tts-0.6b-customvoice-mlx-bf16",
    "distil-whisper_distil-large-v3_594MB",
    "openai_whisper-large-v3-v20240930_626MB",
    "openai_whisper-tiny",
    "gpt-5.6-luna",
    "gpt-5.6-sol",
    "gpt-5.6-terra",
    "qwen3-asr-0.6b-int8",
    "sense-voice-small-int8",
  ]

  private static let reasonCodes: Set<String> = [
    "action-begin-failed", "action-finish-failed",
    "busy",
    "application-shutdown",
    "cancelled",
    "cloudConfirmationRequired",
    "configuration",
    "conditionFailed",
    "contextRestricted",
    "entry-too-large",
    "eventKindMismatch",
    "excludedByCaptureTag",
    "expired",
    "final-replacement-failed",
    "focus-or-selection-moved",
    "allActionsSkipped",
    "invalid-entry",
    "invalid-workflow-enabled-states",
    "invalid-workflow-library",
    "initial-write-failed",
    "initialSilenceTimedOut",
    "inputEndedUnexpectedly",
    "maximumDurationReached",
    "recordMissing",
    "recordChanged",
    "loopPrevented",
    "not-found",
    "overlapping-run",
    "paste-failed",
    "paste-finished",
    "policyBlocked",
    "permission-missing",
    "privacyBlocked",
    "privacySettingsUnavailable",
    "processing",
    "processingDestinationUnavailable",
    "protection-unavailable",
    "request-failed",
    "retry-outcome-unknown",
    "rollback-failed",
    "rule-source-unavailable",
    "run-finished-without-commit",
    "settings-read-failed",
    "settings-write-failed",
    "speechEnded",
    "sourceCollectionMismatch",
    "storage-unavailable",
    "secure-input",
    "selection-moved-before-insert",
    "tail-write-failed",
    "target-content-changed",
    "target-moved-before-commit",
    "transport-failed",
    "trust-material-unavailable",
    "unclassified",
    "unsupported",
    "unsupported-payload",
    "unsupported-target",
    "workflowDisabled",
  ]

  private static let outcomeCodes: Set<String> = [
    "applied",
    "authentication-failed",
    "blocked",
    "cleanup-pending",
    "completed",
    "cancelled",
    "configuration-invalid",
    "credential-unavailable",
    "failed",
    "incomplete",
    "invalid-response",
    "limited",
    "load-failed",
    "network-failed",
    "no-valid-keyterms",
    "none-requested",
    "partial",
    "partially-applied",
    "pending",
    "preserved",
    "rate-limited",
    "refused",
    "resolved",
    "restored",
    "skipped",
    "skipped-change-count",
    "timed-out",
    "unsupported-model",
    "unsupported-recognizer",
    "write-failed",
  ]

  private static let privacyDecisionCodes: Set<String> = [
    "allow",
    "blockCloudProcessing",
    "redactContext",
    "requireCloudConfirmation",
    "skipClipboardCapture",
    "skipWorkflowCapture",
  ]

  private static let privacyReasonCodes: Set<String> = [
    "autoGeneratedClipboard",
    "cloudConfirmationRequired",
    "cloudProcessingBlocked",
    "cloudProviderSelected",
    "concealedClipboard",
    "itemTaggedExcludeFromWorkflowCapture",
    "privacySettingsUnavailable",
    "processingDestinationUnavailable",
    "secureInput",
    "sensitiveApplication",
    "transientClipboard",
    "unknownFocusContext",
    "userDisabledClipboardHistory",
  ]

  /// Diagnostic metadata is deny-by-default. Each retained key has a narrow value grammar.
  private static let metadataAllowlist: [String: MetadataValueKind] = [
    "actionCount": .count,
    "actionID": .closed(actionIDs),
    "activationRevision": .count,
    "acousticAboveThresholdDurationMilliseconds": .count,
    "acousticMaximumConsecutiveAboveThresholdDurationMilliseconds": .count,
    "acousticObservedDurationMilliseconds": .count,
    "acousticObservedSegmentCount": .count,
    "acousticPeakLevelPercentBucket": .count,
    "applicationCount": .count,
    "binding": .closed(["hotkey", "manual", "menuBar", "wakeWord"]),
    "blockReason": .closed([
      "invalid-pending-state",
      "state-read-failed",
      "state-write-failed",
    ]),
    "candidateSetCount": .count,
    "recordPanelShortcut": .closed([
      "disabled-by-preference",
      "enabled",
      "unavailable",
    ]),
    "recordRemovedCount": .count,
    "controlMode": .closed(["holdToTalk", "toggle"]),
    "commandVInterception": .closed([
      "conditional",
      "disabled-by-preference",
      "unavailable",
    ]),
    "count": .count,
    "credentialKey": .closed(["provider.whisperkit.model-token"]),
    "decision": .closed(privacyDecisionCodes),
    "decisions": .closedList(privacyDecisionCodes),
    "defaultModel": .closed([
      "qwen3-asr-0.6b-int8",
      "sense-voice-small-int8",
    ]),
    "deliveryCompleted": .boolean,
    "diagnosticRemovedCount": .count,
    "durationMillis": .count,
    "firstPreviewObservedMillis": .count,
    "stablePreviewObservedMillis": .count,
    "captureTailSampleCount": .count,
    "previewDeliveredSampleCount": .count,
    "previewRequestedKeytermCount": .count,
    "previewKeytermStatus": .closed(["notRequested", "unsupported", "applied", "unavailable"]),
    "captureStopMillis": .count,
    "captureDrainMillis": .count,
    "capturePreviewRetireMillis": .count,
    "captureFinalizeMillis": .count,
    "captureFinishMillis": .count,
    "captureSealMillis": .count,
    "captureCueMillis": .count,
    "pasteDispatchMillis": .count,
    "pasteSettleMillis": .count,

    "modelID": .closed(providerModels),
    "runtime": .closed(["disabled"]),
    "workerIsolation": .closed(["subprocess"]),
    "event": .eventCode,
    "eventKind": .closed(["recordCreated", "recordEdited", "recordRemoved"]),
    "eventSourceState": .closed(["privateState"]),
    "eventTap": .closed(["cghidEventTap"]),
    "failureCode": .closed([
      "busy",
      "cancelled",
      "configuration",
      "invalid-managed-audio",
      "invalidAudio",
      "invalidRequest",
      "invalidText",
      "modelUnavailable",
      "model-disabled",
      "noSpeech",
      "processing",
      "protocol-violation",
      "recognitionFailed",
      "request-already-active",
      "request-timed-out",
      "stale-response",
      "settings-unavailable",
      "synthesisFailed",
      "unclassified",
      "unsupportedModel",
      "unsupportedProtocol",
      "worker-disconnected",
      "worker-termination-failed",
      "worker-unavailable",
    ]),
    "fileCount": .count,
    "gesture": .closed(["control-option-shift-space", "fn-hold"]),
    "groupCount": .count,
    "hasImage": .boolean,
    "historyCount": .count,
    "hotwordCount": .count,
    "hotwordCandidateCount": .count,
    "hotwordCache": .closed(["disabled", "ineligible", "privacy", "hit", "miss", "unavailable"]),
    "hotwordRankingOutcome": .closed(["ready", "cancelled", "timeout", "unavailable"]),
    "hotwordOmittedCount": .count,
    "hotwordOutcome": .closed(["supported", "unsupported-recognizer"]),
    "hotwordRejectedCount": .count,
    "httpStatusCode": .integer,
    "httpStatusClass": .closed(["1xx", "2xx", "3xx", "4xx", "5xx"]),
    "issueCount": .count,
    "keychainKeyState": .closed([
      "alternate-key-retained",
      "matching-key-retained",
      "single-key",
    ]),
    "lane": .closed(["assistant", "interactive"]),
    "modelCount": .count,
    "vadModel": .closed(["silero-vad-v4"]),
    "vocabularyCollectionCount": .count,
    "outcome": .closed(outcomeCodes),
    "omittedCount": .count,
    "pendingCount": .count,
    "pendingReason": .closed([
      "logical-deletion-failed",
      "physical-purge-failed",
      "state-removal-failed",
      "state-write-failed",
    ]),
    "preservedActiveRecordCount": .count,
    "protectedActionCount": .count,
    "protections": .closedList(["autoGenerated", "concealed", "transient"]),
    "pushToTalk": .closed(["active", "unavailable"]),
    "provider": .closed(providerIDs),
    "provider.kind": .closed(providerKinds),
    "provider.model": .closed(providerModels),
    "provider.prompt_tokens": .count,
    "provider.keyterms_used": .count,
    "provider.keyterms_omitted": .count,
    "reason": .closed(reasonCodes),
    "reasons": .closedList(privacyReasonCodes),
    "recognizer.language": .closed(["auto", "en", "en-US", "zh", "zh-CN"]),
    "recognizerID": .closed(recognizerIDs),
    "rejectedCount": .count,
    "replacementCount": .count,
    "requestedTrigger": .closed(["hotkey", "manual", "menuBar", "wakeWord"]),
    "resultCode": .closed([
      "completed",
      "thenBranch",
      "elseBranch",
      "armed",
      "blocked",
      "copiedToClipboard",
      "cancelled",
      "committed",
      "externalOutput",
      "failed",
      "fallback",
      "injected",
      "pushedToStack",
      "storedRecord",
      "rolled-back",
      "skipped",
    ]),
    "retrySafe": .boolean,
    "revision": .count,
    "runRemovedCount": .count,
    "runReceiptRemovedCount": .count,
    "source": .closed([
      "builtin",
      "dashboard.run",
      "hotkey.run",
      "live",
      "long-recording",
      "menu-bar.run",
      "prerecorded",
      "push-to-talk",
      "startup",
      "tests",
      "wake-word.run",
    ]),
    "stage": .closed([
      "capturingInput",
      "saving",
      "completed",
      "delivering",
      "failed",
      "integrity",
      "preparing",
      "recognizing",
      "resolution",
      "resolving",
      "runtime",
      "tokenizer",
      "trust-material-unavailable",
      "trustRoot",
      "transforming",
      "unverified",
    ]),
    "state": .closed([
      "active",
      "armingIgnoreNextExternalChange",
      "ignoringNextExternalChange",
      "paused",
      "pausing",
      "resuming",
    ]),
    "status": .integer,
    "statusCode": .integer,
    "stepCount": .count,
    "stepKind": .closed([
      "recognizeSpeech",
      "applyVocabulary",
      "conditional",
      "resolveUncertainty",
      "llmAnswer",
      "llmRewrite",
      "normalizeWhitespace",
      "snippetReplacement",
    ]),
    "strategy": .closed([
      "clipboardOnly", "collectionFirst", "immediate", "stackFirst", "systemClipboardOnly",
    ]),
    "targetFocusActivationAttempted": .boolean,
    "targetFocusActivationSucceeded": .boolean,
    "targetFocusInitiallyMatched": .boolean,
    "targetFocusProvided": .boolean,
    "targetFocusVerified": .boolean,
    "temporaryFileFailureArtifactKinds": .closedList([
      "audio-capture",
      "live-capture",
      "recognition-work",
      "recovery-audio",
      "shortcut-text",
    ]),
    "temporaryFileFailureCount": .count,
    "temporaryFileFailureOperations": .closedList([
      "enumerate-temporary-directory",
      "inspect-artifact",
      "inspect-temporary-directory",
      "remove-artifact",
    ]),
    "temporaryFileRemovedCount": .count,
    "textLengthBucket": .closed(["empty", "1-16", "17-64", "65-256", "257+"]),
    "totalRemovedCount": .count,
    "transformerID": .closed(transformerIDs),
    "trigger": .closed(["hotkey", "manual", "menuBar", "wakeWord"]),
    "vocabularyApplicationCount": .count,
    "vocabularyIssueCount": .count,
  ]

  public static func sanitize(_ event: DiagnosticEvent) -> DiagnosticEvent {
    var sanitized = event
    sanitized.message = sanitizedMessage
    sanitized.metadata = event.metadata.reduce(into: [:]) { result, entry in
      guard
        let kind = metadataAllowlist[entry.key],
        isSafe(entry.value, as: kind)
      else {
        return
      }
      result[entry.key] = entry.value
    }
    return sanitized
  }

  /// Diagnostic event names are persisted as coordinates rather than content.
  /// Only package-owned protocol values cross this plaintext boundary.
  public static func sanitizeEventCode(_ eventCode: String) -> String {
    eventCodeCatalog.contains(eventCode) ? eventCode : invalidEventCode
  }

  private static func isSafe(_ value: String, as kind: MetadataValueKind) -> Bool {
    guard !containsSensitiveSyntax(value) else { return false }

    switch kind {
    case .boolean:
      return ["false", "off", "on", "true"].contains(value)
    case .closed(let allowedValues):
      return allowedValues.contains(value)
    case .closedList(let allowedValues):
      let values = value.split(separator: ",", omittingEmptySubsequences: false)
      return !values.isEmpty && values.allSatisfy { allowedValues.contains(String($0)) }
    case .count:
      guard value.count <= 20, let count = UInt64(value) else { return false }
      return String(count) == value
    case .eventCode:
      return eventCodeCatalog.contains(value)
    case .integer:
      guard value.count <= 20, let number = Int64(value) else { return false }
      return String(number) == value
    }
  }

  private static func containsSensitiveSyntax(_ value: String) -> Bool {
    let lowercaseValue = value.lowercased()
    let forbiddenFragments = [
      "authorization",
      "bearer ",
      "file://",
      "token=",
      "api_key",
      "apikey",
      "x-api-key",
      "://",
      "/users/",
      "/home/",
      "/private/",
      "/var/folders/",
    ]
    return forbiddenFragments.contains { lowercaseValue.contains($0) }
      || value.contains("?")
      || value.contains("\n")
      || value.contains("\r")
  }
}
