import Foundation

public enum PrivacyDecision: String, Codable, Sendable, Equatable, CaseIterable {
    case allow
    case redactContext
    case skipClipboardCapture
    case skipWorkflowCapture
    case requireCloudConfirmation
    case blockCloudProcessing
}

public enum PrivacyReason: String, Codable, Sendable, Equatable, CaseIterable {
    case sensitiveApplication
    case secureInput
    case userDisabledClipboardHistory
    case cloudProviderSelected
    case itemTaggedExcludeFromWorkflowCapture
    case unknownFocusContext
    case concealedClipboard
    case transientClipboard
    case autoGeneratedClipboard
    case privacySettingsUnavailable
}

public enum PrivacyHistoryPreviewMode: String, Codable, Sendable, Equatable, CaseIterable {
    case full
    case restricted
    case disabled
}

public enum PrivacyProcessingDestination: String, Codable, Sendable, Equatable, CaseIterable {
    case localSpeech
    case cloudSpeech
    case cloudText

    public var isCloud: Bool {
        switch self {
        case .localSpeech:
            return false
        case .cloudSpeech, .cloudText:
            return true
        }
    }
}

public struct SensitiveAppRule: Identifiable, Codable, Sendable, Equatable {
    public var id: UUID
    public var bundleIdentifier: String
    public var applicationName: String?
    public var blocksClipboardHistory: Bool
    public var blocksWorkflowCapture: Bool
    public var blocksSelectedText: Bool
    public var blocksCloudProcessing: Bool
    public var enabled: Bool

    public init(
        id: UUID = UUID(),
        bundleIdentifier: String,
        applicationName: String? = nil,
        blocksClipboardHistory: Bool = true,
        blocksWorkflowCapture: Bool = true,
        blocksSelectedText: Bool = true,
        blocksCloudProcessing: Bool = true,
        enabled: Bool = true
    ) {
        self.id = id
        self.bundleIdentifier = bundleIdentifier
        self.applicationName = applicationName
        self.blocksClipboardHistory = blocksClipboardHistory
        self.blocksWorkflowCapture = blocksWorkflowCapture
        self.blocksSelectedText = blocksSelectedText
        self.blocksCloudProcessing = blocksCloudProcessing
        self.enabled = enabled
    }

    public func matches(focus: FocusSnapshot) -> Bool {
        guard enabled else { return false }
        let normalizedBundle = bundleIdentifier.normalizedPrivacyIdentifier
        if !normalizedBundle.isEmpty,
           let focusedBundle = focus.bundleIdentifier?.normalizedPrivacyIdentifier,
           !focusedBundle.isEmpty {
            return focusedBundle == normalizedBundle
        }

        guard let normalizedName = applicationName?.normalizedPrivacyIdentifier,
              !normalizedName.isEmpty else {
            return false
        }
        return focus.applicationName?.normalizedPrivacyIdentifier == normalizedName
    }
}

public enum SensitiveAppRuleValidationError: Error, LocalizedError, Sendable, Equatable {
    case missingBundleIdentifier
    case invalidBundleIdentifier
    case duplicateBundleIdentifier
    case duplicateRuleIdentifier
    case recommendedRuleCannotBeEdited
    case ruleNotFound

    public var errorDescription: String? {
        switch self {
        case .missingBundleIdentifier:
            return "A bundle identifier is required."
        case .invalidBundleIdentifier:
            return "Enter a valid reverse-DNS bundle identifier, such as com.example.Vault."
        case .duplicateBundleIdentifier:
            return "A sensitive app rule already uses this bundle identifier."
        case .duplicateRuleIdentifier:
            return "The sensitive app rules contain duplicate identifiers."
        case .recommendedRuleCannotBeEdited:
            return "Recommended rule identities cannot be edited or deleted."
        case .ruleNotFound:
            return "The sensitive app rule no longer exists."
        }
    }
}

public extension SensitiveAppRule {
    static let recommendedDefaults: [SensitiveAppRule] = [
        SensitiveAppRule(
            id: privacyStaticUUID("A2F0C099-8E52-4ACD-9B0D-000000000001"),
            bundleIdentifier: "com.1password.1password",
            applicationName: "1Password"
        ),
        SensitiveAppRule(
            id: privacyStaticUUID("A2F0C099-8E52-4ACD-9B0D-000000000002"),
            bundleIdentifier: "com.agilebits.onepassword7",
            applicationName: "1Password 7"
        ),
        SensitiveAppRule(
            id: privacyStaticUUID("A2F0C099-8E52-4ACD-9B0D-000000000003"),
            bundleIdentifier: "com.bitwarden.desktop",
            applicationName: "Bitwarden"
        ),
        SensitiveAppRule(
            id: privacyStaticUUID("A2F0C099-8E52-4ACD-9B0D-000000000004"),
            bundleIdentifier: "org.keepassxc.keepassxc",
            applicationName: "KeePassXC"
        ),
        SensitiveAppRule(
            id: privacyStaticUUID("A2F0C099-8E52-4ACD-9B0D-000000000005"),
            bundleIdentifier: "com.apple.keychainaccess",
            applicationName: "Keychain Access"
        ),
        SensitiveAppRule(
            id: privacyStaticUUID("A2F0C099-8E52-4ACD-9B0D-000000000006"),
            bundleIdentifier: "com.apple.Passwords",
            applicationName: "Passwords"
        ),
    ]

    static var recommendedRuleIDs: Set<UUID> {
        Set(recommendedDefaults.map(\.id))
    }

    var isRecommended: Bool {
        Self.recommendedRuleIDs.contains(id)
    }

    var displayName: String {
        let name = applicationName?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        return name.isEmpty ? bundleIdentifier : name
    }

    var normalizedBundleIdentifier: String {
        bundleIdentifier.normalizedPrivacyIdentifier
    }

    func normalizedAndValidated() throws -> SensitiveAppRule {
        var normalized = self
        normalized.bundleIdentifier = bundleIdentifier.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !normalized.bundleIdentifier.isEmpty else {
            throw SensitiveAppRuleValidationError.missingBundleIdentifier
        }
        guard normalized.bundleIdentifier.isValidPrivacyBundleIdentifier else {
            throw SensitiveAppRuleValidationError.invalidBundleIdentifier
        }

        let name = applicationName?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        normalized.applicationName = name.isEmpty ? nil : name
        return normalized
    }

    static func mergingRecommendedDefaults(
        with storedRules: [SensitiveAppRule]
    ) throws -> [SensitiveAppRule] {
        let normalizedRules = try storedRules.map { try $0.normalizedAndValidated() }
        let identifiers = normalizedRules.map(\.id)
        guard Set(identifiers).count == identifiers.count else {
            throw SensitiveAppRuleValidationError.duplicateRuleIdentifier
        }

        var consumedIndexes: Set<Int> = []
        var mergedRules: [SensitiveAppRule] = []
        var seenBundleIdentifiers: Set<String> = []

        for recommended in recommendedDefaults {
            let matches = normalizedRules.indices.filter { index in
                let candidate = normalizedRules[index]
                return candidate.id == recommended.id
                    || candidate.normalizedBundleIdentifier == recommended.normalizedBundleIdentifier
            }
            guard matches.count <= 1 else {
                throw SensitiveAppRuleValidationError.duplicateBundleIdentifier
            }

            var merged = recommended
            if let index = matches.first {
                consumedIndexes.insert(index)
                let stored = normalizedRules[index]
                merged.blocksClipboardHistory = stored.blocksClipboardHistory
                merged.blocksWorkflowCapture = stored.blocksWorkflowCapture
                merged.blocksSelectedText = stored.blocksSelectedText
                merged.blocksCloudProcessing = stored.blocksCloudProcessing
                merged.enabled = stored.enabled
            }
            mergedRules.append(merged)
            seenBundleIdentifiers.insert(merged.normalizedBundleIdentifier)
        }

        var customRules: [SensitiveAppRule] = []
        for index in normalizedRules.indices where !consumedIndexes.contains(index) {
            let rule = normalizedRules[index]
            guard !rule.isRecommended else {
                throw SensitiveAppRuleValidationError.recommendedRuleCannotBeEdited
            }
            guard seenBundleIdentifiers.insert(rule.normalizedBundleIdentifier).inserted else {
                throw SensitiveAppRuleValidationError.duplicateBundleIdentifier
            }
            customRules.append(rule)
        }
        customRules.sort {
            let nameComparison = $0.displayName.localizedCaseInsensitiveCompare($1.displayName)
            if nameComparison != .orderedSame {
                return nameComparison == .orderedAscending
            }
            return $0.normalizedBundleIdentifier < $1.normalizedBundleIdentifier
        }
        return mergedRules + customRules
    }

    static func restoringRecommendedDefaults(
        whileKeepingCustomRules rules: [SensitiveAppRule]
    ) throws -> [SensitiveAppRule] {
        let customRules = rules.filter { !$0.isRecommended }
        return try mergingRecommendedDefaults(with: customRules)
    }
}

public struct PrivacyPolicySettings: Codable, Sendable, Equatable {
    public var sensitiveAppRules: [SensitiveAppRule]
    public var cloudConfirmationRequired: Bool
    public var historyPreviewMode: PrivacyHistoryPreviewMode
    public var secureInputConservativeMode: Bool

    public init(
        sensitiveAppRules: [SensitiveAppRule] = SensitiveAppRule.recommendedDefaults,
        cloudConfirmationRequired: Bool = true,
        historyPreviewMode: PrivacyHistoryPreviewMode = .restricted,
        secureInputConservativeMode: Bool = true
    ) {
        self.sensitiveAppRules = sensitiveAppRules
        self.cloudConfirmationRequired = cloudConfirmationRequired
        self.historyPreviewMode = historyPreviewMode
        self.secureInputConservativeMode = secureInputConservativeMode
    }

    public static let defaults = PrivacyPolicySettings()
}

public struct PrivacyPolicyDecision: Codable, Sendable, Equatable {
    public var decisions: [PrivacyDecision]
    public var reasons: [PrivacyReason]
    public var redactedContext: ContextSnapshot?
    public var redactedPromptVariables: [PromptVariableKey]
    public var metadata: [String: String]

    public init(
        decisions: [PrivacyDecision] = [.allow],
        reasons: [PrivacyReason] = [],
        redactedContext: ContextSnapshot? = nil,
        redactedPromptVariables: [PromptVariableKey] = [],
        metadata: [String: String] = [:]
    ) {
        self.decisions = decisions
        self.reasons = reasons
        self.redactedContext = redactedContext
        self.redactedPromptVariables = redactedPromptVariables
        self.metadata = metadata
    }

    public var allowsClipboardCapture: Bool {
        !decisions.contains(.skipClipboardCapture)
    }

    public var allowsWorkflowCapture: Bool {
        !decisions.contains(.skipWorkflowCapture)
    }

    public var requiresCloudConfirmation: Bool {
        decisions.contains(.requireCloudConfirmation)
    }

    public var blocksCloudProcessing: Bool {
        decisions.contains(.blockCloudProcessing)
    }
}

public enum PrivacyPolicy {
    public static func evaluate(
        context: ContextSnapshot,
        workflow: WorkflowDefinition? = nil,
        preferredSpeechEngine: PreferredSpeechEngine? = nil,
        processingDestinations: [PrivacyProcessingDestination] = [],
        settings: PrivacyPolicySettings = .defaults
    ) -> PrivacyPolicyDecision {
        var builder = PrivacyPolicyDecisionBuilder(context: context)
        let matchingRule = settings.sensitiveAppRules.first { $0.matches(focus: context.focus) }
        let usesCloud = usesCloudProcessing(
            workflow: workflow,
            preferredSpeechEngine: preferredSpeechEngine,
            processingDestinations: processingDestinations
        )

        if context.clipboard.protections.contains(.concealed) {
            builder.addDecision(.skipClipboardCapture, reason: .concealedClipboard)
            builder.addDecision(.skipWorkflowCapture, reason: .concealedClipboard)
            builder.redact(.clipboard)
        }

        if context.clipboard.protections.contains(.transient) {
            builder.addDecision(.skipClipboardCapture, reason: .transientClipboard)
            builder.addDecision(.skipWorkflowCapture, reason: .transientClipboard)
            builder.redact(.clipboard)
        }

        if context.clipboard.protections.contains(.autoGenerated) {
            builder.addDecision(.skipClipboardCapture, reason: .autoGeneratedClipboard)
            builder.addDecision(.skipWorkflowCapture, reason: .autoGeneratedClipboard)
            builder.redact(.clipboard)
        }

        if context.focus.secureInput, settings.secureInputConservativeMode {
            builder.addDecision(.redactContext, reason: .secureInput)
            builder.addDecision(.skipClipboardCapture, reason: .secureInput)
            builder.addDecision(.skipWorkflowCapture, reason: .secureInput)
            builder.redact(.selected)
            builder.redact(.clipboard)
        }

        if context.clipboard.excludesWorkflowCapture {
            builder.addDecision(.skipWorkflowCapture, reason: .itemTaggedExcludeFromWorkflowCapture)
            builder.redact(.clipboard)
            builder.metadata["privacy.clipboard.tag"] = ClipboardCaptureTag.excludeFromWorkflowCapture.rawValue
        }

        if let matchingRule {
            builder.addReason(.sensitiveApplication)
            builder.metadata["privacy.sensitive.bundleID"] = matchingRule.bundleIdentifier
            builder.metadata["privacy.sensitive.application"] = matchingRule.applicationName ?? ""

            if matchingRule.blocksSelectedText
                || matchingRule.blocksClipboardHistory
                || matchingRule.blocksWorkflowCapture
            {
                builder.addDecision(.redactContext, reason: .sensitiveApplication)
            }
            if matchingRule.blocksSelectedText {
                builder.redact(.selected)
            }
            if matchingRule.blocksClipboardHistory {
                builder.addDecision(.skipClipboardCapture, reason: .sensitiveApplication)
                builder.redact(.clipboard)
            }
            if matchingRule.blocksWorkflowCapture {
                builder.addDecision(.skipWorkflowCapture, reason: .sensitiveApplication)
                builder.redact(.clipboard)
            }
            if matchingRule.blocksCloudProcessing, usesCloud {
                builder.addDecision(.blockCloudProcessing, reason: .sensitiveApplication)
            }
        }

        if usesCloud, settings.cloudConfirmationRequired {
            builder.addDecision(.requireCloudConfirmation, reason: .cloudProviderSelected)
        }

        let hasUnknownFocusContext =
            context.focus.bundleIdentifier?.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
                != false
                && context.focus.applicationName?.trimmingCharacters(in: .whitespacesAndNewlines)
                .isEmpty != false
        if hasUnknownFocusContext {
            builder.addDecision(.redactContext, reason: .unknownFocusContext)
            builder.addDecision(.skipClipboardCapture, reason: .unknownFocusContext)
            builder.addDecision(.skipWorkflowCapture, reason: .unknownFocusContext)
            builder.redact(.selected)
            builder.redact(.clipboard)
            if usesCloud {
                builder.addDecision(.blockCloudProcessing, reason: .unknownFocusContext)
            }
        }

        return builder.build()
    }

    private static func usesCloudProcessing(
        workflow: WorkflowDefinition?,
        preferredSpeechEngine: PreferredSpeechEngine?,
        processingDestinations: [PrivacyProcessingDestination]
    ) -> Bool {
        if processingDestinations.contains(where: \.isCloud) {
            return true
        }
        if preferredSpeechEngine == .cloud {
            return true
        }
        guard let recognizerID = workflow?.pipeline.recognizerID.normalizedPrivacyIdentifier else {
            return false
        }
        return recognizerID.contains("deepgram")
            || recognizerID.contains("cloud")
            || recognizerID.contains("remote")
    }
}

public extension ContextSnapshot {
    func applying(_ decision: PrivacyPolicyDecision) -> ContextSnapshot {
        decision.redactedContext ?? self
    }
}

private struct PrivacyPolicyDecisionBuilder {
    var decisions: [PrivacyDecision] = []
    var reasons: [PrivacyReason] = []
    var metadata: [String: String] = [:]

    private let originalContext: ContextSnapshot
    private var redactedContext: ContextSnapshot?
    private var redactedPromptVariables: [PromptVariableKey] = []

    init(context: ContextSnapshot) {
        originalContext = context
        metadata["privacy.focus.bundleID"] = context.focus.bundleIdentifier ?? ""
        metadata["privacy.focus.application"] = context.focus.applicationName ?? ""
    }

    mutating func addDecision(_ decision: PrivacyDecision, reason: PrivacyReason) {
        appendUnique(decision, to: &decisions)
        addReason(reason)
    }

    mutating func addReason(_ reason: PrivacyReason) {
        appendUnique(reason, to: &reasons)
    }

    mutating func redact(_ variable: PromptVariableKey) {
        appendUnique(variable, to: &redactedPromptVariables)
        if redactedContext == nil {
            redactedContext = originalContext
        }

        switch variable {
        case .selected:
            redactedContext?.focus.selectedText = ""
        case .clipboard:
            redactedContext?.clipboard.plainText = ""
            redactedContext?.clipboard.imagePNGData = nil
            redactedContext?.clipboard.fileURLs = []
        case .text, .rawText, .app, .bundleID, .group:
            break
        }
    }

    func build() -> PrivacyPolicyDecision {
        PrivacyPolicyDecision(
            decisions: decisions.isEmpty ? [.allow] : decisions,
            reasons: reasons,
            redactedContext: redactedContext,
            redactedPromptVariables: redactedPromptVariables,
            metadata: metadata
        )
    }
}

private func appendUnique<T: Equatable>(_ value: T, to values: inout [T]) {
    if !values.contains(value) {
        values.append(value)
    }
}

private func privacyStaticUUID(_ string: String) -> UUID {
    guard let uuid = UUID(uuidString: string) else {
        preconditionFailure("Invalid UUID string: \(string)")
    }
    return uuid
}

private extension String {
    var normalizedPrivacyIdentifier: String {
        trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
    }

    var isValidPrivacyBundleIdentifier: Bool {
        guard utf8.count <= 255 else { return false }
        let components = split(separator: ".", omittingEmptySubsequences: false)
        guard components.count >= 2 else { return false }
        return components.allSatisfy { component in
            let bytes = component.utf8
            guard let first = bytes.first,
                  let last = bytes.last,
                  isASCIIAlphanumeric(first),
                  isASCIIAlphanumeric(last) else {
                return false
            }
            return bytes.allSatisfy { byte in
                isASCIIAlphanumeric(byte) || byte == 0x2D
            }
        }
    }
}

private func isASCIIAlphanumeric(_ byte: UInt8) -> Bool {
    (0x30 ... 0x39).contains(byte)
        || (0x41 ... 0x5A).contains(byte)
        || (0x61 ... 0x7A).contains(byte)
}
