import Foundation

/// A content-free outcome for previewing the privacy gate without granting an
/// authorization or consuming a cloud-processing confirmation.
public enum PrivacyRunEvaluationStatus: String, Codable, Sendable, Equatable, CaseIterable {
    case ready
    case requiresConfirmation
    case blocked
}

/// Stable privacy reasons safe to retain in an explanation receipt or UI state.
///
/// This type intentionally does not carry application identities, policy
/// metadata, captured context, or underlying error descriptions.
public enum PrivacyRunEvaluationReason: String, Codable, Sendable, Equatable, CaseIterable {
    case sensitiveApplication
    case secureInput
    case userDisabledClipboardHistory
    case cloudProviderSelected
    case itemTaggedExcludeFromWorkflowCapture
    case unknownFocusContext
    case concealedClipboard
    case transientClipboard
    case autoGeneratedClipboard
    case cloudProcessingBlocked
    case cloudConfirmationRequired
    case privacySettingsUnavailable
    case processingDestinationUnavailable
}

public enum PrivacyRedactedInputCategory: String, Codable, Sendable, Equatable, CaseIterable {
    case focusedSelection
    case clipboardText
}

/// A privacy-safe projection of `PrivacyPolicyDecision`.
///
/// Only closed enums cross this boundary. In particular, the projection cannot
/// contain `ContextSnapshot`, policy metadata, application identifiers, text,
/// paths, endpoints, credentials, or arbitrary error strings.
public struct PrivacyRunEvaluation: Codable, Sendable, Equatable {
    public var status: PrivacyRunEvaluationStatus
    public var reasons: [PrivacyRunEvaluationReason]
    public var redactedInputCategories: [PrivacyRedactedInputCategory]

    public init(
        status: PrivacyRunEvaluationStatus,
        reasons: [PrivacyRunEvaluationReason] = [],
        redactedInputCategories: [PrivacyRedactedInputCategory] = []
    ) {
        self.status = status
        self.reasons = reasons
        self.redactedInputCategories = redactedInputCategories
    }
}
